services:
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - nodust_kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 4
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  sensor:
    build:
      context: ./sensor
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      NUM_SITES: 1
      SLEEP_MS: 10
      STDDEV_MS: 0
      EVENT_TIMESTAMP_RATE_MS: 900000
      METRIC_MEAN: 0
      METRIC_STD_DEV: 5
      TOPIC: site-sensor-raw
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped

  spark-master:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spark-master
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - nodust_spark_data:/opt/spark/work-dir

  spark-worker-1:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spark-worker-1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1500M
      SPARK_WORKER_CORES: 3
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    command: >
        /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker 
        spark://spark-master:7077
    volumes:
      - nodust_spark_data:/opt/spark/work-dir

  spark-worker-2:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spark-worker-2
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 1500M
      SPARK_WORKER_CORES: 3
    ports:
      - "8082:8081"
    depends_on:
      - spark-master
    command: >
        /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker 
        spark://spark-master:7077
    volumes:
      - nodust_spark_data:/opt/spark/work-dir

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    volumes:
      # - ./local/db:/var/lib/postgresql/data
      - ./system/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: ["postgres", "-c", "log_statement=all"]

  spark-dataflow:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
      sensor:
        condition: service_started
      spark-master:
        condition: service_started
      spark-worker-1:
        condition: service_started
      spark-worker-2:
        condition: service_started
    volumes:
      - ./system:/opt/spark-apps/system
      - ./main.py:/opt/spark-apps/main.py
    environment:
      SPARK_MODE: submit
      SPARK_MASTER_URL: spark://spark-master:7077
      SENSOR_TOPIC: site-sensor-raw
      INTERNAL_ALERTS_TOPIC: alerts_internal
      SEVERE_ALERTS_TOPIC: alerts_severe
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      POSTGRES_URI: "postgresql+psycopg2://postgres:password@postgres:5432/DB"
      ALGORITHM: FuzzyThresholding
    command: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      --num-executors 2
      --executor-cores 1
      --executor-memory 1G
      --driver-memory 512m
      --packages org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.1
      --conf spark.driver.extraJavaOptions="-Divy.cache.dir=/tmp -Divy.home=/tmp"
      /opt/spark-apps/main.py --mode all

  daily-rollup:
    image: postgres:16-alpine
    depends_on:
      - postgres
    environment:
      PGPASSWORD: password
    command: >
      sh -c "
      echo '* * * * * psql -h postgres -U postgres -d DB -c \"CALL compute_daily_averages();\"' > /etc/crontabs/root &&
      crond -f -d 8
      "

volumes:
    nodust_kafka_data:
    nodust_spark_data:
